#!/usr/bin/env python3
"""
Quick Start Script for Small-World Analysis
Generated by SmallWorldIntegrationGuide
"""

import database as db
from run_small_world_analysis import run_quick_analysis, run_visualization_analysis

def main():
    print("🌐 Small-World Network Quick Start")
    print("="*40)
    
    # Option 1: Quick analysis
    print("\n1. Running quick analysis (p=0.1)...")
    try:
        result = run_quick_analysis(p_value=0.1, num_runs=2, steps_per_run=50)
        print("✅ Quick analysis completed!")
    except Exception as e:
        print(f"❌ Quick analysis failed: {e}")
    
    # Option 2: Visualization
    print("\n2. Creating visualizations...")
    try:
        visualizer, stats = run_visualization_analysis(p_value=0.1)
        if stats:
            print(f"✅ Visualization completed! Sigma = {stats['sigma']:.3f}")
    except Exception as e:
        print(f"❌ Visualization failed: {e}")
    
    print("\n🎉 Small-world analysis complete!")
    print("Check generated files for detailed results.")

if __name__ == "__main__":
    main()
